# Generated by Django 5.1.5 on 2025-01-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_blogtagindexpage_blogpagetag_blogpage_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="tags",
        ),
    ]
