# Generated by Django 5.1.5 on 2025-01-20 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_blogpage_tags"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="feed_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="private_field",
            field=models.CharField(default="some_default_value", max_length=255),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="published_date",
            field=models.DateTimeField(default="2024-1-20"),
        ),
    ]
