# Generated by Django 5.1.5 on 2025-01-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_homepage_hero_cta_homepage_hero_cta_link_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
    ]
